language: php

php:
    - 7.2
    - 7.3
    - 7.4

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source

script:
    - ./vendor/bin/phpcs
    - ./vendor/bin/phpunit --configuration phpunit.xml.dist
